Upgrading Conscrypt to 2.5.1 (backport of #7342 to 1.32.x)
grpc/grpc-java pull request #7411
Opened 2020-09-10 18:58 UTC by veblush

backport of #7342 to 1.32.x

2020-09-18 22:57 UTC, voidzcy approved these changes

2020-09-23 15:02 UTC, ejona86 requested changes
We typically don't upgrade to new minor versions of dependencies in a patch release, unless there were serious bugs. This provides a performance improvement, which isn't normally acceptable for a patch release/backport. And upgrading to Conscrypt 2.5.1 required working through a lot of problems, such that it seems this upgrade is more risky than most.

2020-09-23 17:30 UTC, veblush commented
Thank you for the comment! Closing this PR.

2020-09-23 17:30 UTC, closed without merging

2020-09-23 18:02 UTC, ejona86 commented
In talking "offline," we realized that we don't probably need the Conscrypt upgrade; we just need the revert and users are free to upgrade Conscrypt themselves. That would be a fine approach.