Mention Android 11 package visibility in docs.
grpc/grpc-java pull request #9189
Opened 2022-05-20 13:32 UTC by markb74

Android 11 package visibility is a common reason for a binding to fail during development, so mention this in the docs.

2022-05-20 15:47 UTC, jdcormie requested changes
Thanks! This updates the "Detailed Discussion" section. Could you also add this case to the main "Status Code Mapping" table? (Here's the internal version: https://docs.google.com/document/d/1LOw_OXOpfJvWZpKRvJBf08zGTq-wHduE-RqaarCcyOw/edit#bookmark=id.y0ftetnau75m)

2023-06-16 15:48 UTC, ejona86 commented
Do we still want to do this?

2024-09-21 00:05 UTC, larry-safran commented
@jdcormie The requested document to be updated isn't in this repo, so they seem to be separate actions.  Should this go in or should we close it?

2024-09-23 20:07 UTC, jdcormie commented
> @jdcormie The requested document to be updated isn't in this repo, so they seem to be separate actions. Should this go in or should we close it?

No, I was asking for an update to the "Status Code Mapping" table in that same `documentation/android-binderchannel-status-codes.md` doc. My link to the internal doc was to show how I had already addressed this in the gdoc version . 

Sent you https://github.com/grpc/grpc-java/pull/11551 which contains Mark's edit plus the additions I requested.

2024-09-23 20:25 UTC, closed without merging