core: Only use subchannel policy for default target when RLS is not available
grpc/grpc-java pull request #9383
Opened 2022-07-16 06:34 UTC by larry-safran

When RLS returns a value, even when there are no okay subchannels, still return the value from the picker.  Only fallback to the default target when RLS can't communicate.

Fixes #9237

2022-07-18 17:47 UTC, ejona86 reviewed
Let's try to avoid the sleep.

2022-07-18 19:28 UTC, ejona86 approved these changes

2022-07-19 15:49 UTC, ejona86 requested changes
The history is now busted.

2022-07-19 18:58 UTC, ejona86 commented
This PR is for "rls" not "core". The commit/PR title is incorrect.

2022-07-19 19:16 UTC, ejona86 commented
The change still looks busted.

2022-07-19 20:07 UTC, larry-safran commented
Finally got rid of the changes to xds_k8s_lb.sh.

2022-07-20 19:39 UTC, ejona86 approved these changes

2022-07-21 00:20 UTC, merged